name: Dev Container CI

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - '.devcontainer/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Dev Container image
      run: docker build . --file .devcontainer/Dockerfile
